image: node:18-alpine

stages:
  # - build_image
  - deploy

cache:
  key: new-cache
  paths:
    - node_modules/

docker_build:
  stage: build_image
  image: docker:27.3.1
  services:
    - docker:27.3.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

# kaniko_build:
#   stage: build_image
#   image:
#     name: gcr.io/kaniko-project/executor:v1.23.2-debug
#     entrypoint: [""]
#   script:
#     - /kaniko/executor
#       --context "${CI_PROJECT_DIR}"
#       --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
#       --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
#       --cache=true
#       --snapshot-mode=redo
#       --use-new-run

deploy:
  image: kroniak/ssh-client
  stage: deploy
  script:
    - chmod 400 $SSH_PRIVATE_KEY
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY fit@172.23.200.109 "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY fit@172.23.200.109 "docker pull $CI_REGISTRY_IMAGE:latest"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY fit@172.23.200.109 "docker run -d -p 3030:3000 $CI_REGISTRY_IMAGE:latest"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY fit@172.23.200.109 "docker ps"
